troubleshoot postbuild

diff --git a/postBuild b/postBuild
--- a/postBuild
+++ b/postBuild
@@ -16,4 +16,23 @@ Rscript - <<'EOF'
   })
 EOF
 
-cp -r fonts/* /srv/conda/envs/notebook/fonts
+# Install fonts
+# set the source and destination paths
+src_path="/home/runner/micromamba/envs/environment/fonts"
+alt_src_path="/srv/conda/envs/notebook/fonts/"
+
+# check if the source path exists after extracting the fonts
+if [ -d "$src_path" ]; then
+    # if it exists, copy the files to the destination path
+    cp -r fonts/* "$src_path"
+else
+    # if it doesn't exist, check if the alternate source path exists
+    if [ -d "$alt_src_path" ]; then
+        # if it exists, copy the files to the destination path
+        cp -r fonts/* "$alt_src_path"
+    else
+        # if neither directory exists, print an error message
+        echo "Error: fonts directory not found"
+        exit 1
+    fi
+fi
